name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Copy mscorlib for debugging
      run: 
        mkdir -p tests/TestResults/debugging
        cp ~/.dotnet/shared/Microsoft.NETCore.App/3.1.2/mscorlib.dll tests/TestResults/mscorlib.dll
        cp ~/.dotnet/shared/Microsoft.NETCore.App/3.1.2/mscordbi.dll tests/TestResults/mscordbi.dll
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test --blame --blame-hang-timeout 5m --results-directory tests/TestResults
    - name: Archive test results
      if: ${{ ! cancelled() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: tests/TestResults
    - name: Pack with dotnet
      run: dotnet pack --configuration Release --output output
    - name: Publish NuGet
      run: dotnet nuget push -s https://api.nuget.org/v3/index.json -k ${NUGET_API_KEY} --skip-duplicate ./output/*.nupkg
      env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }} 